name: "Publish slides"

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Test it
        run: |
          pwd
          ls

      # - name: Deploy Github Pages ğŸš€
      #   uses: JamesIves/github-pages-deploy-action@4.1.5
      #   with:
      #     branch: gh-pages
      #     folder: ../slides/
      #     clean: true
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}